### ISSUE TITLE
Actividad1_Proposiciones

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-KarenIMont#1]
[PROPOSICIONES_P1.pdf](https://github.com/user-attachments/files/17532891/PROPOSICIONES_P1.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
Calificacion 20
